build:
    environment:
        python:
            version: stackless-3.9

            # Whether to setup a virtual environment in the repository root directory.
            # Defaults to true if omitted.
            virtualenv: true